/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade03;

/**
 *
 * @author fabricio
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    public view() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAno = new javax.swing.JLabel();
        spnAno = new javax.swing.JSpinner();
        bunCalcular = new javax.swing.JButton();
        LblIdade = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAno.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblAno.setText("Informe sua data de nascimento");
        getContentPane().add(lblAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 50, 292, 46));

        spnAno.setModel(new javax.swing.SpinnerNumberModel(2025, 1920, 2025, 1));
        getContentPane().add(spnAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 51, 75, 46));

        bunCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade03/calculadora(1).png"))); // NOI18N
        bunCalcular.setText("Calcular");
        bunCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bunCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(bunCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 180, 80));

        LblIdade.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        LblIdade.setText("Idade");
        getContentPane().add(LblIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        txtResultado.setText("0");
        getContentPane().add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 200, -1));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade03/calendario.png"))); // NOI18N
        getContentPane().add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 210, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bunCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bunCalcularActionPerformed
        // TODO add your handling code here:
        int anoNascimento = (int) spnAno.getValue();
    int anoAtual = java.util.Calendar.getInstance().get(java.util.Calendar.YEAR);

    // Validação simples para garantir que o ano seja plausível
    if (anoNascimento > anoAtual || anoNascimento < 1900) {
        txtResultado.setText("Ano inválido");
    } else {
        int idade = anoAtual - anoNascimento;
        txtResultado.setText(Integer.toString(idade));
    }
    }//GEN-LAST:event_bunCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblIdade;
    private javax.swing.JButton bunCalcular;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblImage;
    private javax.swing.JSpinner spnAno;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
