/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade05;

/**
 *
 * @author fabricio
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    public view() {
        initComponents();

        lblMensagem.setText("<html>Vou pensar em um numero entre 1 e 5:<br>Acerte se for capaz!</html>");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        painel = new javax.swing.JPanel();
        lblImagem = new javax.swing.JLabel();
        lblPalpite = new javax.swing.JLabel();
        spinnerPalpite = new javax.swing.JSpinner();
        bntPalpite = new javax.swing.JButton();
        lblMensagem = new javax.swing.JLabel();
        lblBalaofala = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setForeground(new java.awt.Color(153, 255, 255));

        painel.setBackground(new java.awt.Color(255, 255, 255));
        painel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade05/images.jpeg"))); // NOI18N
        painel.add(lblImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 222, 240));

        lblPalpite.setText("Valor do palpite");
        painel.add(lblPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 235, 116, 33));

        spinnerPalpite.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        painel.add(spinnerPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 239, 128, -1));

        bntPalpite.setText("Palpite");
        bntPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPalpiteActionPerformed(evt);
            }
        });
        painel.add(bntPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 327, 156, 59));
        painel.add(lblMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 230, 110));

        lblBalaofala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade05/balao-de-fala(3).png"))); // NOI18N
        painel.add(lblBalaofala, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 300, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPalpiteActionPerformed
    // Gera número aleatório entre 1 e 5
        int numeroSorteado = 1 + (int) (Math.random() * 5);

    // Obtém o palpite do usuário
        int palpite = (Integer) spinnerPalpite.getValue();

    // Mensagem base
        String mensagem = "";
    // Verifica se acertou
        if (palpite == numeroSorteado) {
             mensagem += "Você acertou! inclivel! ";
        } else {
            mensagem += "Você errou, tente novamente! ";
        }

    // Exibe a mensagem na caixa de texto (com quebra de linha visual)
        lblMensagem.setText(mensagem);
    }//GEN-LAST:event_bntPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntPalpite;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblBalaofala;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblPalpite;
    private javax.swing.JPanel painel;
    private javax.swing.JSpinner spinnerPalpite;
    // End of variables declaration//GEN-END:variables
}
